Lessons.add({
  _id: 'variables',
  title: 'Make your game remember things with variables',
  sections: [
    sec('Types of memory',
        "To understand how to build programs with code, you need to learn a little bit about how computers remember things. Just like your brain, your computer has <b>memory</b>. Computers use two major types of memory, one for short-term needs, and one for long-term needs. For short-term memory, computers use a type of memory called <b>Random Access Memory (RAM)</b>.",
        "Computers store information, or data, in RAM that they need to know right now or in the very near future. This usually includes everything that is currently running on your computer or device, and the operating system itself. So, the web browser you are using right now is running in your computer's RAM.",
        "Other types of information, like files or images that you save by downloading them get stored in a different type of memory called <b>long-term storage</b>. You will learn more about this type of memory in later lessons.")
  ],
  questions: [
    question('What type of memory do you think your computer uses for a game when you are currently playing the game?',
             choice('Long-term storage', 'Probably not. Here\'s why: if the browser wanted to remember your name forever and ever, this would be correct! But, since the browser is simply remembering your name long enough to display it back to you immediately, it only needs to store your name in RAM. However, in a later lesson, we will show you have to make your browser remember your name with drive space forever.'),
             choice('RAM', 'That\'s right! Since the computer needs to access all the data for a game when you are actively playing it, the computer needs to load the game into <b>Random Access Memory (RAM)</b>.', true)
            ),
    question('What type of memory do you think your computer uses for a game that you have downloaded from the internet and saved, but have not yet played?',
             choice('Long-term storage', 'Good job! When your computer transfers data across the internet and saves it for you, it is using <b>long-term storage</b>, typically a <b>hard drive</b> for desktop or laptop computers. or a <b>memory card</b> for phones or other smaller devices. By saving the game there, the computer remembers it for you so that you can play it later.', true),
             choice('RAM', 'This is probably not right. Some games that you access on the internet get loaded immediately into your web browser or device, but typically these do not get <b>saved</b> into the computer\'s <b>long-term storage</b>. Games that you can download and save to play later normally get saved into <b>long-term storage</b>, such a <b>hard drive</b> or <b>memory card</b>.')
            )
  ],
  steps: [
    step('faveColor', 'Your first line of code, I do declare', 'undeclared-variable', expect(null,'ReferenceError: faveColor is not defined'), 'You get this error because you first need to tell your computer to recognize <code>faveColor</code> as a <b>variable</b>. A variable lets you store information in the computer\'s RAM. This is easy to do. To learn how, click next...'),
    step('var faveColor', 'Use the var keyword to declare a variable in memory', 'declare-variable', expect(undefined), 'You just used your first JavaScript language keyword, <code>var</code> to tell the computer to reserve a place in memory named <code>faveColor</code>, but right now it is like an empty brain cell waiting to be filled with information. The response <code>undefined</code> is a type of <b>value</b> that represents a variable that does not have any other assigned value. To get the computer to remember your favorite color, you have to learn about another type of value, and then about <b>variable assignment</b>. Keep going...'),
    step('red', 'Another undeclared variable error message from the interpreter', 'undeclared-variable-red', expect(null,'ReferenceError: red is not defined'), 'An error again? The reason is the same as before. The computer does not recognize <b>red</b> as defined variable. But, there is a simple way to use that color name, and any other, in a way that the computer recognizes as a <b>string</b> type...'),
    step('"red\"', 'Type a string value using double-quotes around text', 'string-variable', expect('"red"'), 'Now you\'re getting somewhere! When the console simply echoes <b>"red"</b> back to you it is telling you that you sent it a value that it could process. In this case, because we surrounded the three characters <b>red</b> with a pair of <b>"</b> characters, the computer recognizes it as a <b>string</b> type. There are several other types of values you can type in that you will learn about later, but try typing each of the following, but do not surround them by <code>"</code> characters just to get a preview:  <p><ul><li>44</li><li>1.5</li><li>true</li><li>false</li></ul></p><p>Let\'s keep going for now...</p>'),
    step('faveColor = "red"', 'Assign a string value into the faveColor variable to make it remember', 'assign-string-value', expect('"red"'), 'Now you have <i>assigned</i> the <b>value</b> of <i>"red"</i> into the <b>variable</b> named <i>faveColor</i>! This is a big step in learning how to code. You really cannot do anything else without mastering this step, so good job! At this point, your computer will forever remember "red" inside of the variable faveColor until you reassign the value, close this page, or leave your computer on long enough that it runs out of power and shuts down! TODO more info')
  ],
  finish: finish('fix-broken-congrats', 'Fix the broken congrats message!', 'var winnerName;\nprompt("Congratulations! What is your name?");\nalert("Great job, " + winnerName + "!");', 'Now that you have learned about variables, try to fix the broken code that asked for your name when you beat the level before:', "return winnerName", "_.isString(val)")
});